#!/bin/bash

# sat6_push.sh
# a script to perform a "hammer export" of everything available on this (local) satellite

TARFILE=/var/lib/pulp/exports/temp/$(date +%Y%m%d)-CDNincr.tar
INCRDIR=/var/lib/pulp/exports/MPO-Default_Organization_View-v1.0-incremental/MPO/Library/
BASEURL="https://10.0.93.8/file/satelite6/"
MAX_SIZE=500M

# first export the entire Sat6 Library since two days ago:

HAMMERTIME="/usr/bin/hammer --password password content-view version export --content-view-id 1 --organization-id 1 --since $(date -d 'last week' +%Y-%m-%dT00:00:00)"
echo $HAMMERTIME
#$HAMMERTIME

# tar everything up
TARCMD="/usr/bin/tar -cvf ${TARFILE} -C ${INCRDIR} ."
echo $TARCMD
$TARCMD

BUNDLE_NAME="/var/lib/pulp/exports/bundles/satbundle"

split -d -b ${MAX_SIZE} ${TARFILE} ${TARFILE}.
# count the number of files split created
TOTALCNT=$(ls ${TARFILE}.?? | wc -l)
for file in $(ls ${TARFILE}.??)
do
  if [ -f ${file}.transfer ]
  then
    echo "Skipping ${file}, as it already has a transfer file present."
    continue
  fi
  echo Converting Docker Bundle ${file}
  echo "This is a file generated by Red Hat in order to assist scanners, which are having trouble reading the verified Red Hat data below.  Please contact taylor@redhat.com if you have any concerns or issues." > ${file}.txt
  md5sum ${file} >> ${file}.txt
  echo >> ${file}.txt
  cat ${file} | base64 >> ${file}.txt
  rm ${file}
  echo Uploading Bundle ${file}
  curl -k -f -T ${file}.txt ${BASEURL}$(basename ${file})of${TOTALCNT}.txt > ${file}.transfer
done

